// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/executor.proto

package executor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Match execution status
type MatchStatus int32

const (
	MatchStatus_STATUS_UNKNOWN   MatchStatus = 0
	MatchStatus_STATUS_SUCCESS   MatchStatus = 1
	MatchStatus_STATUS_TIMEOUT   MatchStatus = 2
	MatchStatus_STATUS_ERROR     MatchStatus = 3
	MatchStatus_STATUS_CANCELLED MatchStatus = 4
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_SUCCESS",
		2: "STATUS_TIMEOUT",
		3: "STATUS_ERROR",
		4: "STATUS_CANCELLED",
	}
	MatchStatus_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_SUCCESS":   1,
		"STATUS_TIMEOUT":   2,
		"STATUS_ERROR":     3,
		"STATUS_CANCELLED": 4,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_executor_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_proto_executor_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

// Request to run a match
type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                 // Unique match identifier
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`                        // Environment name (e.g., "pong")
	Agents        []*AgentData           `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`                                  // List of agents (usually 2)
	TimeoutSec    uint32                 `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`       // Match timeout in seconds
	RecordReplay  bool                   `protobuf:"varint,5,opt,name=record_replay,json=recordReplay,proto3" json:"record_replay,omitempty"` // Whether to record replay data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_proto_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MatchRequest) GetAgents() []*AgentData {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *MatchRequest) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *MatchRequest) GetRecordReplay() bool {
	if x != nil {
		return x.RecordReplay
	}
	return false
}

// Agent data for match execution
type AgentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                              // Unique agent identifier
	CodeUrl       string                 `protobuf:"bytes,2,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`                                                              // URL or path to agent code (deprecated)
	DockerImage   string                 `protobuf:"bytes,5,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`                                                  // Docker image for agent execution
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                             // Agent version
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentData) Reset() {
	*x = AgentData{}
	mi := &file_proto_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentData) ProtoMessage() {}

func (x *AgentData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentData.ProtoReflect.Descriptor instead.
func (*AgentData) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{1}
}

func (x *AgentData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentData) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

func (x *AgentData) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *AgentData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentData) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response from match execution
type MatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MatchId          string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                                // Match identifier
	Status           MatchStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=executor.MatchStatus" json:"status,omitempty"`                      // Match status
	WinnerAgentId    string                 `protobuf:"bytes,3,opt,name=winner_agent_id,json=winnerAgentId,proto3" json:"winner_agent_id,omitempty"`            // Winner agent ID (empty if draw)
	AgentResults     []*AgentResult         `protobuf:"bytes,4,rep,name=agent_results,json=agentResults,proto3" json:"agent_results,omitempty"`                 // Results for each agent
	ReplayUrl        string                 `protobuf:"bytes,5,opt,name=replay_url,json=replayUrl,proto3" json:"replay_url,omitempty"`                          // URL to replay file (if recorded)
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                 // Error message if failed
	TotalSteps       uint32                 `protobuf:"varint,7,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`                      // Total steps executed
	ExecutionTimeSec float64                `protobuf:"fixed64,8,opt,name=execution_time_sec,json=executionTimeSec,proto3" json:"execution_time_sec,omitempty"` // Actual execution time
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_proto_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{2}
}

func (x *MatchResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResponse) GetStatus() MatchStatus {
	if x != nil {
		return x.Status
	}
	return MatchStatus_STATUS_UNKNOWN
}

func (x *MatchResponse) GetWinnerAgentId() string {
	if x != nil {
		return x.WinnerAgentId
	}
	return ""
}

func (x *MatchResponse) GetAgentResults() []*AgentResult {
	if x != nil {
		return x.AgentResults
	}
	return nil
}

func (x *MatchResponse) GetReplayUrl() string {
	if x != nil {
		return x.ReplayUrl
	}
	return ""
}

func (x *MatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MatchResponse) GetTotalSteps() uint32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *MatchResponse) GetExecutionTimeSec() float64 {
	if x != nil {
		return x.ExecutionTimeSec
	}
	return 0
}

// Result for individual agent
type AgentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Errors        uint32                 `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResult) Reset() {
	*x = AgentResult{}
	mi := &file_proto_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResult) ProtoMessage() {}

func (x *AgentResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResult.ProtoReflect.Descriptor instead.
func (*AgentResult) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{3}
}

func (x *AgentResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *AgentResult) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *AgentResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to validate agent code
type ValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CodeZip       []byte                 `protobuf:"bytes,2,opt,name=code_zip,json=codeZip,proto3" json:"code_zip,omitempty"` // Zipped agent code
	Environment   string                 `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`        // Target environment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRequest) Reset() {
	*x = ValidationRequest{}
	mi := &file_proto_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRequest) ProtoMessage() {}

func (x *ValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRequest.ProtoReflect.Descriptor instead.
func (*ValidationRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ValidationRequest) GetCodeZip() []byte {
	if x != nil {
		return x.CodeZip
	}
	return nil
}

func (x *ValidationRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// Response from validation
type ValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	mi := &file_proto_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{6}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ActiveMatches uint32                 `protobuf:"varint,3,opt,name=active_matches,json=activeMatches,proto3" json:"active_matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_executor_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetActiveMatches() uint32 {
	if x != nil {
		return x.ActiveMatches
	}
	return 0
}

var File_proto_executor_proto protoreflect.FileDescriptor

const file_proto_executor_proto_rawDesc = "" +
	"\n" +
	"\x14proto/executor.proto\x12\bexecutor\"\xbe\x01\n" +
	"\fMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12+\n" +
	"\x06agents\x18\x03 \x03(\v2\x13.executor.AgentDataR\x06agents\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\rR\n" +
	"timeoutSec\x12#\n" +
	"\rrecord_replay\x18\x05 \x01(\bR\frecordReplay\"\xfa\x01\n" +
	"\tAgentData\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bcode_url\x18\x02 \x01(\tR\acodeUrl\x12!\n" +
	"\fdocker_image\x18\x05 \x01(\tR\vdockerImage\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.executor.AgentData.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\rMatchResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.executor.MatchStatusR\x06status\x12&\n" +
	"\x0fwinner_agent_id\x18\x03 \x01(\tR\rwinnerAgentId\x12:\n" +
	"\ragent_results\x18\x04 \x03(\v2\x15.executor.AgentResultR\fagentResults\x12\x1d\n" +
	"\n" +
	"replay_url\x18\x05 \x01(\tR\treplayUrl\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vtotal_steps\x18\a \x01(\rR\n" +
	"totalSteps\x12,\n" +
	"\x12execution_time_sec\x18\b \x01(\x01R\x10executionTimeSec\"{\n" +
	"\vAgentResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\rR\x06errors\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"k\n" +
	"\x11ValidationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bcode_zip\x18\x02 \x01(\fR\acodeZip\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\"^\n" +
	"\x12ValidationResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\x14\n" +
	"\x12HealthCheckRequest\"p\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eactive_matches\x18\x03 \x01(\rR\ractiveMatches*q\n" +
	"\vMatchStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x03\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x042\xdf\x01\n" +
	"\bExecutor\x12;\n" +
	"\bRunMatch\x12\x16.executor.MatchRequest\x1a\x17.executor.MatchResponse\x12J\n" +
	"\rValidateAgent\x12\x1b.executor.ValidationRequest\x1a\x1c.executor.ValidationResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.executor.HealthCheckRequest\x1a\x1d.executor.HealthCheckResponseB5Z3github.com/rl-arena/rl-arena-backend/proto;executorb\x06proto3"

var (
	file_proto_executor_proto_rawDescOnce sync.Once
	file_proto_executor_proto_rawDescData []byte
)

func file_proto_executor_proto_rawDescGZIP() []byte {
	file_proto_executor_proto_rawDescOnce.Do(func() {
		file_proto_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)))
	})
	return file_proto_executor_proto_rawDescData
}

var file_proto_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_executor_proto_goTypes = []any{
	(MatchStatus)(0),            // 0: executor.MatchStatus
	(*MatchRequest)(nil),        // 1: executor.MatchRequest
	(*AgentData)(nil),           // 2: executor.AgentData
	(*MatchResponse)(nil),       // 3: executor.MatchResponse
	(*AgentResult)(nil),         // 4: executor.AgentResult
	(*ValidationRequest)(nil),   // 5: executor.ValidationRequest
	(*ValidationResponse)(nil),  // 6: executor.ValidationResponse
	(*HealthCheckRequest)(nil),  // 7: executor.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 8: executor.HealthCheckResponse
	nil,                         // 9: executor.AgentData.MetadataEntry
}
var file_proto_executor_proto_depIdxs = []int32{
	2, // 0: executor.MatchRequest.agents:type_name -> executor.AgentData
	9, // 1: executor.AgentData.metadata:type_name -> executor.AgentData.MetadataEntry
	0, // 2: executor.MatchResponse.status:type_name -> executor.MatchStatus
	4, // 3: executor.MatchResponse.agent_results:type_name -> executor.AgentResult
	1, // 4: executor.Executor.RunMatch:input_type -> executor.MatchRequest
	5, // 5: executor.Executor.ValidateAgent:input_type -> executor.ValidationRequest
	7, // 6: executor.Executor.HealthCheck:input_type -> executor.HealthCheckRequest
	3, // 7: executor.Executor.RunMatch:output_type -> executor.MatchResponse
	6, // 8: executor.Executor.ValidateAgent:output_type -> executor.ValidationResponse
	8, // 9: executor.Executor.HealthCheck:output_type -> executor.HealthCheckResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_executor_proto_init() }
func file_proto_executor_proto_init() {
	if File_proto_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_executor_proto_rawDesc), len(file_proto_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_executor_proto_goTypes,
		DependencyIndexes: file_proto_executor_proto_depIdxs,
		EnumInfos:         file_proto_executor_proto_enumTypes,
		MessageInfos:      file_proto_executor_proto_msgTypes,
	}.Build()
	File_proto_executor_proto = out.File
	file_proto_executor_proto_goTypes = nil
	file_proto_executor_proto_depIdxs = nil
}
